---
title: "Relativistic Cosmology Part 2"
author: "Dr Vicky Scowcroft"
date: "Semester 2, 2019/20"
site: bookdown::bookdown_site
#output:
#  bookdown::tufte_html_book:
#    toc: yes
#    css: [mystyle.css, toc.css]
output: 
  bookdown::gitbook:
    css: [mystyle.css]
bibliography: [book.bib, packages.bib]
documentclass: book
classoption: 
 - a4paper
biblio-style: apalike
link-citations: yes
github-repo: PH40112_rmd
description: "PH40112 Relativistic Cosmology Part 2."
citecolor: magenta
filecolor: black
linkcolor: black
urlcolor: magenta
fontsize: 11pt
subparagraph: yes
#abstract: | 

---
# Unit Overview {-}
  The aim of this section of PH40112 is to present the observations and
  theory underpinning modern Cosmology. It is complementary to the first
  half of PH40112, which focusses on General Relativity and its
  applications to Cosmology. At the end of this course, you should be
  able to describe the key ideas of Cosmology, comparing and contrasting
  different observational techniques and Cosmological models. You should
  understand the implications for the fate of the Universe arising from
  these different models, and discuss the open questions being addressed
  by current state of the art experiments. You should also be able to
  assess how systematic errors and experimental uncertainties affect
  cosmological experiments, in particular how these affect our ability
  to discriminate between different models of the Universe's evolution.
  
## Topics and Schedule {-}

The planned schedule for sessions is as follows:

| Week | Date      |         Session        |                                                              Topic |
|:-----|:----------|:----------------------:|-------------------------------------------------------------------:|
| 7    | 16/3 |        Lecture 1       |                            Introduction to Observational Cosmology |
|      | 19/3  |        Lecture 2       |                                Equations of the Expanding Universe |
|      | 20/3  |        Lecture 3       |                                        Composition of the Universe |
| 8    | 23/3  |        Lecture 4       |                                             Observational Parameters|
|      | 26/3 |        Lecture 5       |                                           Observational Techniques |
|      | 27/3  |        Lecture 6       |                                                        The $\Lambda$CDM Model |
| 9    | 30/3  |        Lecture 7       |                                         Dark Matter |
|      | 2/4  |     **Discussion session** |                        Current Research Topics |  
|      | 3/4  |  Lecture 8       |                                        Structures in the Universe |
| 10   | 20/4  |        Lecture 9       |                                                          Inflation |
|      | 23/4  |       Lecture 10       |                                              The Evolving Universe |
|      | 24/4 |     Problems Class     |                                                     Problems Class |
| 11   | 27/4  |     Problems Class     |                                                     Problems Class |
|      | 30/4  |     Problems Class     |                                                     Problems Class |
|      | 1/5     |    Revision Session    |                                           Revision Session and Q&A |
| 12   | 4/5 - 7/5 |      Office hours      | Revision week. <br>Office hours will be posted closer to the date. |

Lectures have been front-loaded for this section of the course. Problem sheets will be released once the relavent material has been covered, but formal problems classes will not take place until weeks 10 and 11.

The schedule was last updated on 13<sup>th</sup> March. Changes to the planned schedule will be posted here and on the moodle page. 

## Discussion session - Thursday 2<sup>nd</sup>April {-}

The session on Thursday April 2nd will be a discussion session, covering three journal publications using different techniques used to estimate cosmological parameters. You will each be assigned to a group during week 8 and the group assignments and corresponding papers will be posted to Moodle. After the session, summaries of the discussions will be uploaded to Moodle and the relavent section of these notes. 

If the date and/or format of this session needs to change, updates will be posted here and on the Moodle forum. 

## Suggested textbook {-}
  This section of the course closely follows several chapters of *An
  Introduction to Modern Cosmology: 3<sup>rd</sup> edition* by Liddle.
  You may find it helpful to refer to this book or others such as *The
  Oxford companion to Cosmology* by Liddle and Loveday, which is
  available in the University library.

## Lecture notes, slides, recordings {-}

Written notes for lectures 1 - 10 will be made available online in html and PDF format. The html notes are available at https://vickyscowcroft.github.io/PH40112_rmd/ and will be updated throughout the course. PDF versions of the notes will be posted to the course Moodle page. The html notes have been designed so that the maths content is compatible with screen readers. 

Lectures will follow the same general structure as the written notes, but will not be identical - i.e. they will not be `skeleton' notes for you to fill in the blanks. They are designed to support your learning of the lecture material, so you may find it useful to make your own notes during the session. 

PDF versions of the slides for each session will be posted on Moodle before each session. If you need these in an alternative format please let me know. 

All sessions will be recorded with Panopto and can be accessed in the usual way. 


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
